<a href="https://colab.research.google.com/github/TungSoPon/bsc_dpdm22/blob/main/Untitled24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Load google sheet มาตรฐาน

In [1]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

In [6]:
import pandas as pd

In [2]:
gsht = gc.open_by_key('13tZJ1ZQuO6HWzbuZzabmmF_NnZpLAw2TG_eqN_ExU3U')

In [4]:
worksheet = gsht.worksheet("land")

In [8]:
rows = worksheet.get_all_values()
land = pd.DataFrame.from_records(rows)

In [9]:
land

,0,1,2,3,4,5,6,7,8
0,ID ผู้ประเมิน,post id,property_type,ความมั่นใจในการเมินราคาทรัพย์,ราคาทรัพย์,ประเมินราคาซื้อ-ขาย,ปัจจัยในการประเมินราคาซื้อ-ขาย,เหตุผลไม่มั่นใจราคาประเมิน,ให้คะแนนทรัพย์
1,01,https://nayoo.co/khonkaen/posts/1033,ที่ดิน,มั่นใจ,2800000,1800000,"8,000-25,000",,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน
2,02,https://nayoo.co/khonkaen/posts/1033,ที่ดิน,มั่นใจ,2800000,2000000,"ราคาเสนอขาย 7,000-12,0000 บาท/ตารางวา",,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี
3,04,https://nayoo.co/khonkaen/posts/1033,ที่ดิน,มั่นใจ,2800000,2200000,10000-22000,,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี
4,01,https://nayoo.co/khonkaen/posts/1711,ที่ดิน,มั่นใจ,14900000,8000000,"25,000-80,000",,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี
...,...,...,...,...,...,...,...,...,...
206,01,https://nayoo.co/khonkaen/posts/17093,ที่ดิน,มั่นใจ,2650000,2000000,"500-15,000 บาท/ตารางวา",,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี
207,02,https://nayoo.co/khonkaen/posts/17112,ที่ดิน,มั่นใจ,1300000,1500000,"ราคาเสนอขาย 3,000 - 5,000 บาท/ตารางวา",,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน
208,01,https://nayoo.co/khonkaen/posts/17112,ที่ดิน,มั่นใจ,1300000,1500000,"500-25,000 บาท/ตารางวา",,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน
209,02,https://nayoo.co/khonkaen/posts/17145,ที่ดิน,มั่นใจ,3000000,2800000,"ราคาเสนอขาย 10,000 - 15,000 บาท/ตารางวา",,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี
210,01,https://nayoo.co/khonkaen/posts/17145,ที่ดิน,มั่นใจ,3000000,2500000,"1,000-25,000 บาท/ตารางวา",,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน

In [12]:
land.columns = land.iloc[0] #สามารถใส่เองโดยใช้lit
land.head()

,ID ผู้ประเมิน,post id,property_type,ความมั่นใจในการเมินราคาทรัพย์,ราคาทรัพย์,ประเมินราคาซื้อ-ขาย,ปัจจัยในการประเมินราคาซื้อ-ขาย,เหตุผลไม่มั่นใจราคาประเมิน,ให้คะแนนทรัพย์
0,ID ผู้ประเมิน,post id,property_type,ความมั่นใจในการเมินราคาทรัพย์,ราคาทรัพย์,ประเมินราคาซื้อ-ขาย,ปัจจัยในการประเมินราคาซื้อ-ขาย,เหตุผลไม่มั่นใจราคาประเมิน,ให้คะแนนทรัพย์
1,01,https://nayoo.co/khonkaen/posts/1033,ที่ดิน,มั่นใจ,2800000,1800000,"8,000-25,000",,3 ขายได้ ใช้ระยะเวลา 7 - 12 เดือน
2,02,https://nayoo.co/khonkaen/posts/1033,ที่ดิน,มั่นใจ,2800000,2000000,"ราคาเสนอขาย 7,000-12,0000 บาท/ตารางวา",,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี
3,04,https://nayoo.co/khonkaen/posts/1033,ที่ดิน,มั่นใจ,2800000,2200000,10000-22000,,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี
4,01,https://nayoo.co/khonkaen/posts/1711,ที่ดิน,มั่นใจ,14900000,8000000,"25,000-80,000",,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี

In [15]:
land = land.iloc[1:].reset_index().iloc[:,1:] #ตัดคอลัม

In [16]:
land.head()

,ID ผู้ประเมิน,post id,property_type,ความมั่นใจในการเมินราคาทรัพย์,ราคาทรัพย์,ประเมินราคาซื้อ-ขาย,ปัจจัยในการประเมินราคาซื้อ-ขาย,เหตุผลไม่มั่นใจราคาประเมิน,ให้คะแนนทรัพย์
0,02,https://nayoo.co/khonkaen/posts/1033,ที่ดิน,มั่นใจ,2800000,2000000,"ราคาเสนอขาย 7,000-12,0000 บาท/ตารางวา",,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี
1,04,https://nayoo.co/khonkaen/posts/1033,ที่ดิน,มั่นใจ,2800000,2200000,10000-22000,,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี
2,01,https://nayoo.co/khonkaen/posts/1711,ที่ดิน,มั่นใจ,14900000,8000000,"25,000-80,000",,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี
3,02,https://nayoo.co/khonkaen/posts/1711,ที่ดิน,มั่นใจ,14900000,12000000,"ราคาเสนอขาย 100,000-150,000 บาท/ตารางวา",,2 ขายได้ยาก ใช้ระยะเวลามากว่า 1 ปี
4,04,https://nayoo.co/khonkaen/posts/1711,ที่ดิน,ไม่มั่นใจ,14900000,,,ข้อมูลทรัพย์ไม่เพียงพอ,